id = "wakatime"
name = "wakatime"
description = "Wakatime support."
version = "0.1.7"
schema_version = 1
authors = ["bestgopher <84328409@qq.com>"]
repository = "https://github.com/wakatime/zed-wakatime"

[language_servers.wakatime]
name = "wakatime"
languages = [
    "AsciiDoc",
    "Astro",
    "Bash",
    "Biome",
    "C",
    "C++",
    "Clojure",
    "CSharp",
    "CSS",
    "CSV",
    "D",
    "Dart",
    "Elixir",
    "Elm",
    "Erlang",
    "Fish",
    "FSharp",
    "GDScript",
    "Gleam",
    "Go",
    "GraphQL",
    "Haskell",
    "HEEX",
    "HTML",
    "Hy",
    "Idris",
    "Java",
    "JavaScript",
    "JSON",
    "JSONC",
    "Julia",
    "Kotlin",
    "Lua",
    "Markdown",
    "Nim",
    "Nix",
    "OCaml",
    "PureScript",
    "Python",
    "Racket",
    "Roc",
    "Ruby",
    "Rust",
    "Scheme",
    "SCSS",
    "Shell Script",
    "SQL",
    "Swift",
    "TOML",
    "TSX",
    "TypeScript",
    "WIT",
    "XML",
    "YAML",
    "Zig",
]
